### ISSUE TITLE
Werte für Editorvariablen

### ISSUE THREAD

**Issue by ksbbf** [ediarum/ediarum.REGISTER.edit#1]
Leider bekomme ich die Verbindung zu den Registern nicht hin. Meine Werte für die Variablen zum Personen-Register sehen in etwa so aus:

**ediarum_project_domain:**  https://oxygen-bot:*******@mydomain:8443/exist/webdav/db
**ediarum_projects_directory:** /projects
**ediarum_project_name:** /meine_edition/data
**ediarum_index_person:** Register/Personen.xml

Das Ganze ergibt dann etwa so etwas:

^https:// oxygen-bot:****!@mydomain:8443/exist/webdav/db/projects/meine_edition/data/Register/Personen.xml

Oder muss ich die die API-URL nehmen? Dort fehlt aber bei mir das UPDATE & GET...

**Comment by StefanDumont** [comment]
Hallo @ksbbf !

Deine Editorvariablen müssten so aussehen:

- **ediarum_project_domain:** `https://oxygen-bot:*******@mydomain:8443`
- **ediarum_projects_directory:** `/exist/rest/db/projects/` (Slashes vorne und hinten beachten; der Zugriff für die Registerfunktionen wird über `rest` statt `webdav` realisiert)
- **ediarum_project_name:** `meine_edition` (ja, ohne Slashes)
- **ediarum_index_person:** ~~Register/Personen.xml~~ `/oxygen/ediarum.xql?index=persons` (hier muss die automatisch von ediarum angelegte Schnittstelle verwendet werden, nicht die Register-Datei selbst!)

Zusammengesetzt sieht die URL dann so aus: 
`https://oxygen-bot:*******@mydomain:8443/exist/rest/db/projects/meine_edition/oxygen/ediarum.xql?index=persons` - das ist auch die API-URL, die angeboten wird. "UPDATE & GET" gibt es nur bei Verwendung eines Zotero-basierten Registers. Hier müssen die in eXistdb gespeicherten Daten ja mit einer externen Datenquelle (Zotero-Gruppe) abgeglichen (= `UPDATE`) werden. Das ist bei allen anderen Register nicht nötig, weil diese ja direkt in eXistdb gespeichert und gepflegt werden.

Hilft das weiter?

**Comment by ksbbf** [comment]
Herzlichen Dank! Das war's was mit fehlte.

**Comment by tutebatti** [comment]
Hallo,
vielleicht könnte die Dokumentation an dieser Stelle verbessert werden.

In der Zeile zu ${ediarum_project_domain} heißt es "Basis-URL zur Datenbank. Der Wert muss Domain, ggf. Server-Port und Server-Anmeldedaten enthalten.", als Beispiel wird "http://oxygen-bot:******@example.de:8028" angeführt.
> example.de steht für domain
> 8028 für den Port
Wofür aber stehen die anderen Werte im Beispiel? M.a.W., wie ist die Syntax der Werte, die hier angegeben werden müssen?

Unklar ist mir außerdem, warum in der Dokumentation der "Pfad zu den Projekt-Ordnern in der eXist-DB via WebDAV-Verbindung" zusätzlich angegeben wird.

In Schritt 7 heißt es "Prüfen Sie, ob folgende Editorvariablen für die Datenbankanbindung passend zu Ihrer Infrastruktur gesetzt sind." Heißt das, sie sollten normalerweise automatisch gesetzt sein?

**Comment by StefanDumont** [comment]
Hi tutebatti,
tut mir leid, hatte deine Frage hier irgendwie nicht mitbekommen. Hier endlich die Antworten :-) 
* oxygen-bot:**** steht allgemein im HTTP-Protokoll für  `username:password` zum Einloggen. Der Username `oxygen-bot` wird von ediarum automatisch gesetzt, das Passwort ist der App-Oberfläche einstellbar.
* Die zusätzliche Webdav-Verbindung ist für 1-2 Funktionen in ediarum.BASE.edit nötig, insbesondere wenn Querverweise zwischen Dokumenten gesetzt werden sollen. Die Registerfunktionen werden durch eine fehlende Angabe aber nicht berührt.
* Nein, es geht nur darum, wie die existdb installiert wurde. Standardmäßig ist sie nach der Installation unter `https://exampleserver.com:8080/exist/` erreichbar. In einigen Institutionen (so auch bei uns) wird aber die Pfadangabe `/exist/` ersetzt, weil mehrere Instanzen auf dem Server betrieben werden. Das ist halt zu prüfen, ob das bei euch der Fall ist. 

Hoffe, das hilft weiter. Ansonsten gerne rückfragen!
