### ISSUE TITLE
Register löschen

### ISSUE THREAD

**Issue by ksbbf** [ediarum/ediarum.REGISTER.edit#2]
Wie kann ich ein Register im Ediarum-Backend löschen. 

Ich habe eines für Sachbegriffe angelegt, kann es aber im Moment nicht verwenden, da es als Button in Oxygen--Author ausgegraut ist.

**Comment by StefanDumont** [comment]
Einfach die Datei in data/Register löschen. Die Schnittstelle ist ja standardmäßig in ediarum.DB programmiert und muss/kann daher nicht gelöscht werden. Ich übernehme das aber mal als Feature-Request für ediarum.DB, dass ein "Entfernen"-Button vllt. nicht schlecht wäre.

ABER: Die Schaltfläche im Author ist dann ausgegraut, wenn das Schema die Verwendung an dieser Stelle nicht zulässt. Sobald man den Cursor in den Textbereich (TEI/text) setzt, sollte sie nicht mehr ausgegraut sein.
